C:
cd C:\Program Files\Microsoft Office\Office16
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\client-issuance-bridge-office.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\client-issuance-root.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program FilesMicrosoft Office\root\Licenses16\client-issuance-root-bridge-test.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\client-issuance-bridge-office.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\client-issuance-stil.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\client-issuance-ul.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\client-issuance-ul-oob.xrm-ms
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\pkeyconfig-office.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\pkeyconfig-office-client15.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ppd.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ul.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_KMS_Client_AE-ul-oob.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_MAK_AE-pl.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_MAK_AE-ppd.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_MAK_AE-ul-oob.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019VL_MAK_AE-ul-phn.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_KMS_ClientC2R-ppd.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_KMS_ClientC2R-ul.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_KMS_ClientC2R-ul-oob.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_MAKC2R-pl.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_MAKC2R-ppd.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_MAKC2R-ul-oob.xrm-ms"
cscript ospp.vbs /inslic:"C:\Program Files\Microsoft Office\root\Licenses16\ProPlus2019XC2RVL_MAKC2R-ul-phn.xrm-ms"